# Generated by Django 5.2.4 on 2025-07-30 12:36

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('size', models.BigIntegerField()),
                ('category', models.CharField(choices=[('report', 'Research Reports'), ('financial', 'Financial Documents'), ('policy', 'Policy Papers'), ('manual', 'Technical Manuals'), ('legal', 'Legal Documents'), ('marketing', 'Marketing Materials'), ('training', 'Training Resources'), ('other', 'Other')], default='other', max_length=50)),
                ('access_level', models.CharField(choices=[('private', 'Private (Only you)'), ('restricted', 'Restricted (Approved users)'), ('internal', 'Internal (Organization)'), ('public', 'Public (All users)')], default='private', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('rnd', 'Research & Development'), ('finance', 'Finance'), ('legal', 'Legal'), ('marketing', 'Marketing'), ('hr', 'Human Resources'), ('operations', 'Operations'), ('it', 'IT & Security'), ('none', 'None')], default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('encryption_key', models.BinaryField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('semantic_indexing', models.BooleanField(default=True)),
                ('auto_keyword_extraction', models.BooleanField(default=True)),
                ('virus_scanned', models.BooleanField(default=True)),
                ('watermarked', models.BooleanField(default=False)),
                ('audit_trail', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'permissions': [('can_view_restricted', 'Can view restricted documents'), ('can_view_private', 'Can view private documents')],
            },
        ),
    ]
